// Code generated by protoc-gen-go. DO NOT EDIT.
// source: options.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Custom FieldOptions
type FieldOptions struct {
	// Fields tagged with this will be omitted from generated schemas
	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Fields tagged with this will be marked as "required" in generated schemas
	Required bool `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	// Fields tagged with this will constrain strings using the "minLength" keyword in generated schemas
	MinLength int32 `protobuf:"varint,3,opt,name=min_length,json=minLength,proto3" json:"min_length,omitempty"`
	// Fields tagged with this will constrain strings using the "maxLength" keyword in generated schemas
	MaxLength int32 `protobuf:"varint,4,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	// Fields tagged with this will constrain strings using the "pattern" keyword in generated schemas
	Pattern              string   `protobuf:"bytes,5,opt,name=pattern,proto3" json:"pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FieldOptions) Reset()         { *m = FieldOptions{} }
func (m *FieldOptions) String() string { return proto.CompactTextString(m) }
func (*FieldOptions) ProtoMessage()    {}
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{0}
}

func (m *FieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldOptions.Unmarshal(m, b)
}
func (m *FieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldOptions.Marshal(b, m, deterministic)
}
func (m *FieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldOptions.Merge(m, src)
}
func (m *FieldOptions) XXX_Size() int {
	return xxx_messageInfo_FieldOptions.Size(m)
}
func (m *FieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FieldOptions proto.InternalMessageInfo

func (m *FieldOptions) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func (m *FieldOptions) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

func (m *FieldOptions) GetMinLength() int32 {
	if m != nil {
		return m.MinLength
	}
	return 0
}

func (m *FieldOptions) GetMaxLength() int32 {
	if m != nil {
		return m.MaxLength
	}
	return 0
}

func (m *FieldOptions) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

// Custom FileOptions
type FileOptions struct {
	// Files tagged with this will not be processed
	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Override the default file extension for schemas generated from this file
	Extension            string   `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileOptions) Reset()         { *m = FileOptions{} }
func (m *FileOptions) String() string { return proto.CompactTextString(m) }
func (*FileOptions) ProtoMessage()    {}
func (*FileOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{1}
}

func (m *FileOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileOptions.Unmarshal(m, b)
}
func (m *FileOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileOptions.Marshal(b, m, deterministic)
}
func (m *FileOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileOptions.Merge(m, src)
}
func (m *FileOptions) XXX_Size() int {
	return xxx_messageInfo_FileOptions.Size(m)
}
func (m *FileOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_FileOptions.DiscardUnknown(m)
}

var xxx_messageInfo_FileOptions proto.InternalMessageInfo

func (m *FileOptions) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func (m *FileOptions) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

// Custom MessageOptions
type MessageOptions struct {
	// Messages tagged with this will not be processed
	Ignore bool `protobuf:"varint,1,opt,name=ignore,proto3" json:"ignore,omitempty"`
	// Messages tagged with this will have all fields marked as "required":
	AllFieldsRequired bool `protobuf:"varint,2,opt,name=all_fields_required,json=allFieldsRequired,proto3" json:"all_fields_required,omitempty"`
	// Messages tagged with this will additionally accept null values for all properties:
	AllowNullValues bool `protobuf:"varint,3,opt,name=allow_null_values,json=allowNullValues,proto3" json:"allow_null_values,omitempty"`
	// Messages tagged with this will have all fields marked as not allowing additional properties:
	DisallowAdditionalProperties bool `protobuf:"varint,4,opt,name=disallow_additional_properties,json=disallowAdditionalProperties,proto3" json:"disallow_additional_properties,omitempty"`
	// Messages tagged with this will have all nested enums encoded to use constants instead of simple types (supports value annotations):
	EnumsAsConstants     bool     `protobuf:"varint,5,opt,name=enums_as_constants,json=enumsAsConstants,proto3" json:"enums_as_constants,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageOptions) Reset()         { *m = MessageOptions{} }
func (m *MessageOptions) String() string { return proto.CompactTextString(m) }
func (*MessageOptions) ProtoMessage()    {}
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{2}
}

func (m *MessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageOptions.Unmarshal(m, b)
}
func (m *MessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageOptions.Marshal(b, m, deterministic)
}
func (m *MessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageOptions.Merge(m, src)
}
func (m *MessageOptions) XXX_Size() int {
	return xxx_messageInfo_MessageOptions.Size(m)
}
func (m *MessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_MessageOptions proto.InternalMessageInfo

func (m *MessageOptions) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

func (m *MessageOptions) GetAllFieldsRequired() bool {
	if m != nil {
		return m.AllFieldsRequired
	}
	return false
}

func (m *MessageOptions) GetAllowNullValues() bool {
	if m != nil {
		return m.AllowNullValues
	}
	return false
}

func (m *MessageOptions) GetDisallowAdditionalProperties() bool {
	if m != nil {
		return m.DisallowAdditionalProperties
	}
	return false
}

func (m *MessageOptions) GetEnumsAsConstants() bool {
	if m != nil {
		return m.EnumsAsConstants
	}
	return false
}

// Custom EnumOptions
type EnumOptions struct {
	// Enums tagged with this will have be encoded to use constants instead of simple types (supports value annotations):
	EnumsAsConstants bool `protobuf:"varint,1,opt,name=enums_as_constants,json=enumsAsConstants,proto3" json:"enums_as_constants,omitempty"`
	// Enums tagged with this will only provide string values as options (not their numerical equivalents):
	EnumsAsStringsOnly bool `protobuf:"varint,2,opt,name=enums_as_strings_only,json=enumsAsStringsOnly,proto3" json:"enums_as_strings_only,omitempty"`
	// Enums tagged with this will have enum name prefix removed from values:
	EnumsTrimPrefix bool `protobuf:"varint,3,opt,name=enums_trim_prefix,json=enumsTrimPrefix,proto3" json:"enums_trim_prefix,omitempty"`
	// Enums tagged with this will not be processed
	Ignore               bool     `protobuf:"varint,4,opt,name=ignore,proto3" json:"ignore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumOptions) Reset()         { *m = EnumOptions{} }
func (m *EnumOptions) String() string { return proto.CompactTextString(m) }
func (*EnumOptions) ProtoMessage()    {}
func (*EnumOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_110d40819f1994f9, []int{3}
}

func (m *EnumOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumOptions.Unmarshal(m, b)
}
func (m *EnumOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumOptions.Marshal(b, m, deterministic)
}
func (m *EnumOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumOptions.Merge(m, src)
}
func (m *EnumOptions) XXX_Size() int {
	return xxx_messageInfo_EnumOptions.Size(m)
}
func (m *EnumOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumOptions.DiscardUnknown(m)
}

var xxx_messageInfo_EnumOptions proto.InternalMessageInfo

func (m *EnumOptions) GetEnumsAsConstants() bool {
	if m != nil {
		return m.EnumsAsConstants
	}
	return false
}

func (m *EnumOptions) GetEnumsAsStringsOnly() bool {
	if m != nil {
		return m.EnumsAsStringsOnly
	}
	return false
}

func (m *EnumOptions) GetEnumsTrimPrefix() bool {
	if m != nil {
		return m.EnumsTrimPrefix
	}
	return false
}

func (m *EnumOptions) GetIgnore() bool {
	if m != nil {
		return m.Ignore
	}
	return false
}

var E_FieldOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*FieldOptions)(nil),
	Field:         1125,
	Name:          "protoc.gen.jsonschema.field_options",
	Tag:           "bytes,1125,opt,name=field_options",
	Filename:      "options.proto",
}

var E_ManualLink = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50015,
	Name:          "protoc.gen.jsonschema.manual_link",
	Tag:           "bytes,50015,opt,name=manual_link",
	Filename:      "options.proto",
}

var E_IgnoreInAutocomplete = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50000,
	Name:          "protoc.gen.jsonschema.ignore_in_autocomplete",
	Tag:           "varint,50000,opt,name=ignore_in_autocomplete",
	Filename:      "options.proto",
}

var E_FileOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*FileOptions)(nil),
	Field:         1126,
	Name:          "protoc.gen.jsonschema.file_options",
	Tag:           "bytes,1126,opt,name=file_options",
	Filename:      "options.proto",
}

var E_MessageOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*MessageOptions)(nil),
	Field:         1127,
	Name:          "protoc.gen.jsonschema.message_options",
	Tag:           "bytes,1127,opt,name=message_options",
	Filename:      "options.proto",
}

var E_MessageManualLink = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50000,
	Name:          "protoc.gen.jsonschema.message_manual_link",
	Tag:           "bytes,50000,opt,name=message_manual_link",
	Filename:      "options.proto",
}

var E_EnumOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*EnumOptions)(nil),
	Field:         1128,
	Name:          "protoc.gen.jsonschema.enum_options",
	Tag:           "bytes,1128,opt,name=enum_options",
	Filename:      "options.proto",
}

func init() {
	proto.RegisterType((*FieldOptions)(nil), "protoc.gen.jsonschema.FieldOptions")
	proto.RegisterType((*FileOptions)(nil), "protoc.gen.jsonschema.FileOptions")
	proto.RegisterType((*MessageOptions)(nil), "protoc.gen.jsonschema.MessageOptions")
	proto.RegisterType((*EnumOptions)(nil), "protoc.gen.jsonschema.EnumOptions")
	proto.RegisterExtension(E_FieldOptions)
	proto.RegisterExtension(E_ManualLink)
	proto.RegisterExtension(E_IgnoreInAutocomplete)
	proto.RegisterExtension(E_FileOptions)
	proto.RegisterExtension(E_MessageOptions)
	proto.RegisterExtension(E_MessageManualLink)
	proto.RegisterExtension(E_EnumOptions)
}

func init() { proto.RegisterFile("options.proto", fileDescriptor_110d40819f1994f9) }

var fileDescriptor_110d40819f1994f9 = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x56, 0xd8, 0x0f, 0xe9, 0x69, 0xb7, 0xb1, 0x8c, 0x4d, 0xd1, 0xb4, 0x41, 0x55, 0x84, 0x54,
	0x21, 0x94, 0x09, 0xb8, 0xeb, 0x15, 0x63, 0x30, 0x09, 0x69, 0x63, 0xc3, 0xfc, 0x5c, 0x70, 0x63,
	0x79, 0x8d, 0x9b, 0x99, 0x39, 0x76, 0xb0, 0x1d, 0xe8, 0x5e, 0x60, 0x0f, 0xc1, 0x63, 0xf0, 0x24,
	0x7b, 0x03, 0xae, 0xf8, 0x79, 0x04, 0x2e, 0x51, 0xed, 0x24, 0x4d, 0xa1, 0x5b, 0xaf, 0xa2, 0x73,
	0xbe, 0xef, 0xf3, 0xb1, 0xbf, 0x73, 0x4e, 0x60, 0x49, 0x66, 0x86, 0x49, 0xa1, 0xa3, 0x4c, 0x49,
	0x23, 0x83, 0x75, 0xfb, 0xe9, 0x47, 0x09, 0x15, 0xd1, 0x47, 0x2d, 0x85, 0xee, 0x9f, 0xd2, 0x94,
	0x6c, 0xb6, 0x13, 0x29, 0x13, 0x4e, 0x77, 0x2c, 0x7a, 0x92, 0x0f, 0x76, 0x62, 0xaa, 0xfb, 0x8a,
	0x65, 0x46, 0x2a, 0x27, 0xec, 0x7c, 0xf5, 0xa0, 0xb5, 0xcf, 0x28, 0x8f, 0x8f, 0xdc, 0x79, 0xc1,
	0x06, 0x2c, 0xb2, 0x44, 0x48, 0x45, 0x43, 0xaf, 0xed, 0x75, 0x7d, 0x54, 0x44, 0xc1, 0x26, 0xf8,
	0x8a, 0x7e, 0xca, 0x99, 0xa2, 0x71, 0x78, 0xc3, 0x22, 0x55, 0x1c, 0x6c, 0x03, 0xa4, 0x4c, 0x60,
	0x4e, 0x45, 0x62, 0x4e, 0xc3, 0xb9, 0xb6, 0xd7, 0x5d, 0x40, 0x8d, 0x94, 0x89, 0x03, 0x9b, 0xb0,
	0x30, 0x19, 0x96, 0xf0, 0x7c, 0x01, 0x93, 0x61, 0x01, 0x87, 0x70, 0x33, 0x23, 0xc6, 0x50, 0x25,
	0xc2, 0x85, 0xb6, 0xd7, 0x6d, 0xa0, 0x32, 0xec, 0xec, 0x41, 0x73, 0x9f, 0x71, 0x3a, 0xeb, 0x6a,
	0x5b, 0xd0, 0xa0, 0x43, 0x43, 0x85, 0x66, 0x52, 0xd8, 0xbb, 0x35, 0xd0, 0x38, 0xd1, 0xf9, 0xe3,
	0xc1, 0xf2, 0x21, 0xd5, 0x9a, 0x24, 0x33, 0x0f, 0x8a, 0x60, 0x8d, 0x70, 0x8e, 0x07, 0x23, 0x3f,
	0x34, 0xfe, 0xe7, 0xb9, 0xab, 0x84, 0x73, 0xeb, 0x94, 0x46, 0xe5, 0xbb, 0x1f, 0xc0, 0x28, 0x29,
	0xbf, 0x60, 0x91, 0x73, 0x8e, 0x3f, 0x13, 0x9e, 0x53, 0x6d, 0x9f, 0xef, 0xa3, 0x15, 0x0b, 0xbc,
	0xca, 0x39, 0x7f, 0x6f, 0xd3, 0xc1, 0x73, 0xb8, 0x13, 0x33, 0xed, 0xe8, 0x24, 0x8e, 0xd9, 0xe8,
	0x26, 0x84, 0xe3, 0x4c, 0xc9, 0x8c, 0x2a, 0xc3, 0xa8, 0xb6, 0xc6, 0xf8, 0x68, 0xab, 0x64, 0xed,
	0x56, 0xa4, 0xe3, 0x8a, 0x13, 0x3c, 0x84, 0x80, 0x8a, 0x3c, 0xd5, 0x98, 0x68, 0xdc, 0x97, 0x42,
	0x1b, 0x22, 0x8c, 0xb6, 0xb6, 0xf9, 0xe8, 0x96, 0x45, 0x76, 0xf5, 0x5e, 0x99, 0xef, 0x7c, 0xf3,
	0xa0, 0xf9, 0x42, 0xe4, 0x69, 0xf9, 0xee, 0xe9, 0x6a, 0x6f, 0xba, 0x3a, 0x78, 0x04, 0xeb, 0x15,
	0x5b, 0x1b, 0xc5, 0x44, 0xa2, 0xb1, 0x14, 0xfc, 0xbc, 0xf0, 0x23, 0x28, 0x04, 0x6f, 0x1c, 0x74,
	0x24, 0xf8, 0xf9, 0xc8, 0x10, 0x27, 0x31, 0x8a, 0xa5, 0x38, 0x53, 0x74, 0xc0, 0x86, 0xa5, 0x21,
	0x16, 0x78, 0xab, 0x58, 0x7a, 0x6c, 0xd3, 0xb5, 0x26, 0xcc, 0xd7, 0x9b, 0xd0, 0x3b, 0x85, 0x25,
	0xdb, 0x00, 0x5c, 0x4c, 0x78, 0xb0, 0x1d, 0xb9, 0x29, 0x8e, 0xca, 0x29, 0x8e, 0xea, 0x03, 0x1b,
	0xfe, 0xf0, 0xdb, 0x5e, 0xb7, 0xf9, 0xf8, 0x5e, 0x34, 0x75, 0x05, 0x26, 0xb8, 0xa8, 0x35, 0xa8,
	0x45, 0xbd, 0xa7, 0xd0, 0x4c, 0x89, 0xc8, 0x09, 0xc7, 0x9c, 0x89, 0xb3, 0x59, 0x75, 0xbe, 0x5f,
	0xcc, 0xd9, 0xd1, 0x02, 0xa7, 0x39, 0x60, 0xe2, 0xac, 0xf7, 0x0e, 0x36, 0xdc, 0xad, 0x31, 0x13,
	0x98, 0xe4, 0x46, 0xf6, 0x65, 0x9a, 0x71, 0x6a, 0xe8, 0xac, 0xc3, 0x2e, 0x2f, 0x9c, 0x2b, 0xb7,
	0x9d, 0xfc, 0xa5, 0xd8, 0xad, 0x89, 0x7b, 0x31, 0xb4, 0x06, 0x8c, 0xd3, 0xca, 0x81, 0xad, 0x29,
	0x87, 0x55, 0x6b, 0x11, 0xfe, 0x74, 0x06, 0x74, 0xae, 0x34, 0xa0, 0xa2, 0xa2, 0xe6, 0x60, 0x1c,
	0xf4, 0x32, 0x58, 0x49, 0xdd, 0x5e, 0x54, 0x85, 0xee, 0xfe, 0x57, 0x68, 0x72, 0x73, 0xc2, 0x5f,
	0xae, 0xd6, 0xfd, 0x2b, 0x6a, 0x4d, 0xb2, 0xd1, 0x72, 0x3a, 0x11, 0xf7, 0x5e, 0xc3, 0x5a, 0x59,
	0xb1, 0x6e, 0xfc, 0xcc, 0xaa, 0x97, 0x85, 0xf5, 0xab, 0x85, 0xfa, 0x70, 0xdc, 0x81, 0x18, 0x5a,
	0xa3, 0xc1, 0xba, 0xc6, 0xaa, 0xda, 0x02, 0x84, 0xbf, 0xaf, 0xb7, 0xaa, 0x46, 0x45, 0x4d, 0x3a,
	0x0e, 0x9e, 0xc1, 0x07, 0x3f, 0x72, 0x3f, 0x51, 0x7d, 0xb2, 0x68, 0xbf, 0x4f, 0xfe, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x97, 0xf8, 0xe5, 0x16, 0x82, 0x05, 0x00, 0x00,
}
